#!/bin/bash

CONFIG="$HOME/.config/hypr/component/wofi/config"
STYLE="$HOME/.config/hypr/component/wofi/style.css"
COLORS="$HOME/.config/hypr/component/wofi/colors"

if [[ ! $(pidof wofi) ]]; then
	wofi --show drun --prompt 'Search...' --conf ${CONFIG} --style ${STYLE} --color ${COLORS}
else
	pkill wofi
fi
